### PR TITLE
Added emmet-sqlite to workspace

### PR DESCRIPTION
**Pull request by davecosec**

### CODE REVIEW

**Review by oskardudycz — CHANGES_REQUESTED** [review]
@davecosec, could you also add sqlite package to:
- tsconfig - https://github.com/event-driven-io/emmett/blob/ef8e32b771bcf78785d9aa6bd574d6e221104c27/src/tsconfig.json#L32
- eslint config: https://github.com/event-driven-io/emmett/blob/ef8e32b771bcf78785d9aa6bd574d6e221104c27/src/eslint.config.mjs#L96

to complete setup?

The package-lock changes indeed looks suspicious, but might be that those are needed sqlite3 dependencies or peer dependencies 🤷

**Comment by davecosec** [comment]
> The package-lock changes indeed looks suspicious, but might be that those are needed sqlite3 dependencies or peer dependencies 🤷

https://github.com/TryGhost/node-sqlite3/issues/1800 

hrm..

**Comment by oskardudycz** [comment]
> > The package-lock changes indeed looks suspicious, but might be that those are needed sqlite3 dependencies or peer dependencies 🤷
> 
> [TryGhost/node-sqlite3#1800](https://github.com/TryGhost/node-sqlite3/issues/1800)
> 
> hrm..

Let’s keep it as it is, for now, and later consider switching to better sqlite3 if it appears better maintained and fulfilling our needs.

**Review by oskardudycz — APPROVED** [review]

**Comment by oskardudycz** [comment]
Thanks @davecosec, I’m pulling that in 👌

**Pull request merged**
